### ISSUE TITLE
Setter Corrections and Proper Invocations

### ISSUE THREAD

**Issue by alexdeanb** [nss-daytime-cohort-63/Exomine-Team-1#30]
* **I'm submitting a ...**
  - [x ] bug report
  - [x ] feature request

* **What is the current behavior?**
Setters are updating the wrong attribute, needs correction.

Need to update past code with invoking proper setters.

**Comment by Nic-Lahde** [comment]
corrected syntax in addCustomOrder(), added setter for colonyId and Mineral
